export const tags=[
    {
      "name": "Reptiles",
      "slug": "reptiles"
    }, {
      "name": "Snakes",
      "slug": "snakes"
    }, {
      "name": "Boas",
      "slug": "boas"
    }, {
      "name": "AmazonTreeBoas",
      "slug": "amazon-tree-boas"
    }, {
      "name": "Anacondas",
      "slug": "anacondas"
    }, {
      "name": "GreenAnacondas",
      "slug": "green-anacondas"
    }, {
      "name": "YellowAnacondas",
      "slug": "yellow-anacondas"
    }, {
      "name": "BoaConstrictors",
      "slug": "boa-constrictors"
    }, {
      "name": "BrazilianRainbowBoas",
      "slug": "brazilian-rainbow-boas"
    }, {
      "name": "ColombianRainbowBoas",
      "slug": "colombian-rainbow-boas"
    }, {
      "name": "DumerilsBoas",
      "slug": "dumerils-boas"
    }, {
      "name": "EmeraldTreeBoas",
      "slug": "emerald-tree-boas"
    }, {
      "name": "KenyanSandBoas",
      "slug": "kenyan-sand-boas"
    }, {
      "name": "RosyBoas",
      "slug": "rosy-boas"
    }, {
      "name": "RoughScaledSandBoas",
      "slug": "rough-scaled-sand-boas"
    }, {
      "name": "RubberBoas",
      "slug": "rubber-boas"
    }, {
      "name": "SolomonIslandGroundBoas",
      "slug": "solomon-island-ground-boas"
    }, {
      "name": "SolomonIslandTreeBoas",
      "slug": "solomon-island-tree-boas"
    }, {
      "name": "ViperBoas",
      "slug": "viper-boas"
    }, {
      "name": "Pythons",
      "slug": "pythons"
    }, {
      "name": "AfricanRockPythons",
      "slug": "african-rock-pythons"
    }, {
      "name": "AngolanPythons",
      "slug": "angolan-pythons"
    }, {
      "name": "BismarckRingedPythons",
      "slug": "bismarck-ringed-pythons"
    }, {
      "name": "BlackHeadedPythons",
      "slug": "black-headed-pythons"
    }, {
      "name": "BloodPythons",
      "slug": "blood-pythons"
    }, {
      "name": "BoelensPythons",
      "slug": "boelens-pythons"
    }, {
      "name": "BurmesePythons",
      "slug": "burmese-pythons"
    }, {
      "name": "BurrowingPythons",
      "slug": "burrowing-pythons"
    }, {
      "name": "CarpetPythons",
      "slug": "carpet-pythons"
    }, {
      "name": "ChildrensPythons",
      "slug": "childrens-pythons"
    }, {
      "name": "GreenTreePythons",
      "slug": "green-tree-pythons"
    }, {
      "name": "OlivePythons",
      "slug": "olive-pythons"
    }, {
      "name": "ReticulatedPythons",
      "slug": "reticulated-pythons"
    }, {
      "name": "SavuPythons",
      "slug": "savu-pythons"
    }, {
      "name": "SpottedPythons",
      "slug": "spotted-pythons"
    }, {
      "name": "StimsonsPythons",
      "slug": "stimsons-pythons"
    }, {
      "name": "TimorPythons",
      "slug": "timor-pythons"
    }, {
      "name": "WhiteLippedPythons",
      "slug": "white-lipped-pythons"
    }, {
      "name": "WomaPythons",
      "slug": "woma-pythons"
    }, {
      "name": "Colubrids",
      "slug": "colubrids"
    }, {
      "name": "AesculapianSnakes",
      "slug": "aesculapian-snakes"
    }, {
      "name": "AfricanEggEatingSnakes",
      "slug": "african-egg-eating-snakes"
    }, {
      "name": "AfricanHouseSnakes",
      "slug": "african-house-snakes"
    }, {
      "name": "AmericanVineSnakes",
      "slug": "american-vine-snakes"
    }, {
      "name": "AsianVineSnakes",
      "slug": "asian-vine-snakes"
    }, {
      "name": "BandedCatEyeSnakes",
      "slug": "banded-cat-eye-snakes"
    }, {
      "name": "BaronsRacers",
      "slug": "barons-racers"
    }, {
      "name": "BlackHeadedCatSnakes",
      "slug": "black-headed-cat-snakes"
    }, {
      "name": "CommonFileSnakes",
      "slug": "common-file-snakes"
    }, {
      "name": "CornSnake",
      "slug": "corn-snake"
    }, {
      "name": "EasternIndigos",
      "slug": "eastern-indigos"
    }, {
      "name": "FalseWaterCobras",
      "slug": "false-water-cobras"
    }, {
      "name": "GarterSnakes",
      "slug": "garter-snakes"
    }, {
      "name": "GopherSnakes",
      "slug": "gopher-snakes"
    }, {
      "name": "GrassSnakes",
      "slug": "grass-snakes"
    }, {
      "name": "HognoseSnakes",
      "slug": "hognose-snakes"
    }, {
      "name": "TricolorHognoseSnakes",
      "slug": "tricolor-hognose-snakes"
    }, {
      "name": "WesternHognoseSnakes",
      "slug": "western-hognose-snakes"
    }, {
      "name": "MadagascarHognoseSnakes",
      "slug": "madagascar-hognose-snakes"
    }, {
      "name": "Kingsnakes",
      "slug": "kingsnakes"
    }, {
      "name": "ArizonaMountainKingsnakes",
      "slug": "arizona-mountain-kingsnakes"
    }, {
      "name": "BrooksKingsnakes",
      "slug": "brooks-kingsnakes"
    }, {
      "name": "CaliforniaKingsnakes",
      "slug": "california-kingsnakes"
    }, {
      "name": "DesertKingsnakes",
      "slug": "desert-kingsnakes"
    }, {
      "name": "FloridaKingsnakes",
      "slug": "florida-kingsnakes"
    }, {
      "name": "GrayBandedKingsnakes",
      "slug": "gray-banded-kingsnakes"
    }, {
      "name": "MexicanBlackKingsnakes",
      "slug": "mexican-black-kingsnakes"
    }, {
      "name": "MangroveSnakes",
      "slug": "mangrove-snakes"
    }, {
      "name": "MilkSnakes",
      "slug": "milk-snakes"
    }, {
      "name": "PueblanMilkSnakes",
      "slug": "pueblan-milk-snakes"
    }, {
      "name": "HonduranMilkSnake",
      "slug": "honduran-milk-snake"
    }, {
      "name": "NelsonsMilkSnake",
      "slug": "nelsons-milk-snake"
    }, {
      "name": "ParadiseFlyingSnakes",
      "slug": "paradise-flying-snakes"
    }, {
      "name": "PineSnake",
      "slug": "pine-snake"
    }, {
      "name": "PinewoodsSnake",
      "slug": "pinewoods-snake"
    }, {
      "name": "RatSnakes",
      "slug": "rat-snakes"
    }, {
      "name": "BambooRatSnakes",
      "slug": "bamboo-rat-snakes"
    }, {
      "name": "BlackRatSnakes",
      "slug": "black-rat-snakes"
    }, {
      "name": "MandarinRatSnakes",
      "slug": "mandarin-rat-snakes"
    }, {
      "name": "RadiatedRatSnakes",
      "slug": "radiated-rat-snakes"
    }, {
      "name": "RussianRatSnakes",
      "slug": "russian-rat-snakes"
    }, {
      "name": "TexasRatSnakes",
      "slug": "texas-rat-snakes"
    }, {
      "name": "RoughGreenSnakes",
      "slug": "rough-green-snakes"
    }, {
      "name": "ScarletSnakes",
      "slug": "scarlet-snakes"
    }, {
      "name": "TaiwaneseBeautySnakes",
      "slug": "taiwanese-beauty-snakes"
    }, {
      "name": "VietnameseBlueBeautySnakes",
      "slug": "vietnamese-blue-beauty-snakes"
    }, {
      "name": "YellowTailCribos",
      "slug": "yellow-tail-cribos"
    }, {
      "name": "OtherSnakes",
      "slug": "other-snakes"
    }, {
      "name": "RedBeakedSnakes",
      "slug": "red-beaked-snakes"
    }, {
      "name": "SunbeamSnakes",
      "slug": "sunbeam-snakes"
    }, {
      "name": "BandedWaterSnakes",
      "slug": "banded-water-snakes"
    }, {
      "name": "ElephantTrunkSnakes",
      "slug": "elephant-trunk-snakes"
    }, {
      "name": "GreenWaterSnakes",
      "slug": "green-water-snakes"
    }, {
      "name": "TentacledSnakes",
      "slug": "tentacled-snakes"
    }, {
      "name": "Lizards",
      "slug": "lizards"
    }, {
      "name": "Anoles",
      "slug": "anoles"
    }, {
      "name": "BarbudaBankAnoles",
      "slug": "barbuda-bank-anoles"
    }, {
      "name": "BigFannedTrunkAnoles",
      "slug": "big-fanned-trunk-anoles"
    }, {
      "name": "BrownGreenAnoles",
      "slug": "brown-green-anoles"
    }, {
      "name": "CaveAnoles",
      "slug": "cave-anoles"
    }, {
      "name": "CubanKnightAnoles",
      "slug": "cuban-knight-anoles"
    }, {
      "name": "MonkeyAnoles",
      "slug": "monkey-anoles"
    }, {
      "name": "BeardedDragons",
      "slug": "bearded-dragons"
    }, {
      "name": "CentralBeardedDragons",
      "slug": "central-bearded-dragons"
    }, {
      "name": "EasternBeardedDragons",
      "slug": "eastern-bearded-dragons"
    }, {
      "name": "RankinsDragons",
      "slug": "rankins-dragons"
    }, {
      "name": "Chameleons",
      "slug": "chameleons"
    }, {
      "name": "FlapNeckChameleons",
      "slug": "flap-neck-chameleons"
    }, {
      "name": "CubanFalseChameleons",
      "slug": "cuban-false-chameleons"
    }, {
      "name": "VeiledChameleons",
      "slug": "veiled-chameleons"
    }, {
      "name": "CarpetChameleons",
      "slug": "carpet-chameleons"
    }, {
      "name": "PantherChameleons",
      "slug": "panther-chameleons"
    }, {
      "name": "ElliotsChameleons",
      "slug": "elliots-chameleons"
    }, {
      "name": "HelmetedChameleons",
      "slug": "helmeted-chameleons"
    }, {
      "name": "JacksonsChameleons",
      "slug": "jacksons-chameleons"
    }, {
      "name": "JohnstonsChameleons",
      "slug": "johnstons-chameleons"
    }, {
      "name": "SpinyFlankedChameleons",
      "slug": "spiny-flanked-chameleons"
    }, {
      "name": "MellersChameleons",
      "slug": "mellers-chameleons"
    }, {
      "name": "ChineseWaterDragons",
      "slug": "chinese-water-dragons"
    }, {
      "name": "Geckos",
      "slug": "geckos"
    }, {
      "name": "AustralianBarkingGeckos",
      "slug": "australian-barking-geckos"
    }, {
      "name": "AustralianLeafTailedGeckos",
      "slug": "australian-leaf-tailed-geckos"
    }, {
      "name": "ChahouaGeckos",
      "slug": "chahoua-geckos"
    }, {
      "name": "ChameleonGeckos",
      "slug": "chameleon-geckos"
    }, {
      "name": "CrestedGeckos",
      "slug": "crested-geckos"
    }, {
      "name": "DayGeckos",
      "slug": "day-geckos"
    }, {
      "name": "BlueTailedDayGeckos",
      "slug": "blue-tailed-day-geckos"
    }, {
      "name": "GiantDayGeckos",
      "slug": "giant-day-geckos"
    }, {
      "name": "GoldDustDayGeckos",
      "slug": "gold-dust-day-geckos"
    }, {
      "name": "LinedDayGeckos",
      "slug": "lined-day-geckos"
    }, {
      "name": "NeonDayGeckos",
      "slug": "neon-day-geckos"
    }, {
      "name": "PeacockDayGeckos",
      "slug": "peacock-day-geckos"
    }, {
      "name": "StandingsDayGeckos",
      "slug": "standings-day-geckos"
    }, {
      "name": "GoldenGeckos",
      "slug": "golden-geckos"
    }, {
      "name": "HalmaheraGeckos",
      "slug": "halmahera-geckos"
    }, {
      "name": "HouseGeckos",
      "slug": "house-geckos"
    }, {
      "name": "LeafTailedGeckos",
      "slug": "leaf-tailed-geckos"
    }, {
      "name": "LinedGeckos",
      "slug": "lined-geckos"
    }, {
      "name": "MoorishGeckos",
      "slug": "moorish-geckos"
    }, {
      "name": "MourningGeckos",
      "slug": "mourning-geckos"
    }, {
      "name": "NewCaledonianGiantGeckos",
      "slug": "new-caledonian-giant-geckos"
    }, {
      "name": "SarasinorumGeckos",
      "slug": "sarasinorum-geckos"
    }, {
      "name": "TokayGeckos",
      "slug": "tokay-geckos"
    }, {
      "name": "VelvetGeckos",
      "slug": "velvet-geckos"
    }, {
      "name": "YellowHeadedDwarfGeckos",
      "slug": "yellow-headed-dwarf-geckos"
    }, {
      "name": "CentralAmericanBandedGecko",
      "slug": "central-american-banded-gecko"
    }, {
      "name": "WesternBandedGecko",
      "slug": "western-banded-gecko"
    }, {
      "name": "FatTailedGeckos",
      "slug": "fat-tailed-geckos"
    }, {
      "name": "GracefulMadagascarGroundGeckos",
      "slug": "graceful-madagascar-ground-geckos"
    }, {
      "name": "IranianFatTailedGeckos",
      "slug": "iranian-fat-tailed-geckos"
    }, {
      "name": "KnobTailedGeckos",
      "slug": "knob-tailed-geckos"
    }, {
      "name": "KwanghuaCaveGeckos",
      "slug": "kwanghua-cave-geckos"
    }, {
      "name": "LeopardGeckos",
      "slug": "leopard-geckos"
    }, {
      "name": "PictusGeckos",
      "slug": "pictus-geckos"
    }, {
      "name": "ScorpionTailedGeckos",
      "slug": "scorpion-tailed-geckos"
    }, {
      "name": "SpinyTailedGeckos",
      "slug": "spiny-tailed-geckos"
    }, {
      "name": "ViperGeckos",
      "slug": "viper-geckos"
    }, {
      "name": "Iguanas",
      "slug": "iguanas"
    }, {
      "name": "CubanRockIguanas",
      "slug": "cuban-rock-iguanas"
    }, {
      "name": "DesertIguanas",
      "slug": "desert-iguanas"
    }, {
      "name": "FijiIguanas",
      "slug": "fiji-iguanas"
    }, {
      "name": "GreenIguanas",
      "slug": "green-iguanas"
    }, {
      "name": "RhinoIguanas",
      "slug": "rhino-iguanas"
    }, {
      "name": "SpinyTailedIguanas",
      "slug": "spiny-tailed-iguanas"
    }, {
      "name": "Monitors",
      "slug": "monitors"
    }, {
      "name": "ArgusMonitors",
      "slug": "argus-monitors"
    }, {
      "name": "AsianWaterMonitors",
      "slug": "asian-water-monitors"
    }, {
      "name": "BlackTreeMonitors",
      "slug": "black-tree-monitors"
    }, {
      "name": "BlackThroatMonitors",
      "slug": "black-throat-monitors"
    }, {
      "name": "CrocodileMonitors",
      "slug": "crocodile-monitors"
    }, {
      "name": "DumerilsMonitors",
      "slug": "dumerils-monitors"
    }, {
      "name": "GreenTreeMonitors",
      "slug": "green-tree-monitors"
    }, {
      "name": "LaceMonitors",
      "slug": "lace-monitors"
    }, {
      "name": "MertensMonitors",
      "slug": "mertens-monitors"
    }, {
      "name": "NileMonitors",
      "slug": "nile-monitors"
    }, {
      "name": "PilbaraRockMonitors",
      "slug": "pilbara-rock-monitors"
    }, {
      "name": "PygmyRockMonitors",
      "slug": "pygmy-rock-monitors"
    }, {
      "name": "SandMonitors",
      "slug": "sand-monitors"
    }, {
      "name": "SavannahMonitors",
      "slug": "savannah-monitors"
    }, {
      "name": "SpinyTailMonitors",
      "slug": "spiny-tail-monitors"
    }, {
      "name": "TimorMonitors",
      "slug": "timor-monitors"
    }, {
      "name": "WhiteThroatMonitors",
      "slug": "white-throat-monitors"
    }, {
      "name": "YellowHeadedWaterMonitors",
      "slug": "yellow-headed-water-monitors"
    }, {
      "name": "Skinks",
      "slug": "skinks"
    }, {
      "name": "BlueTongueSkinks",
      "slug": "blue-tongue-skinks"
    }, {
      "name": "BlotchedBlueTongueSkinks",
      "slug": "blotched-blue-tongue-skinks"
    }, {
      "name": "CentralianBlueTongueSkinks",
      "slug": "centralian-blue-tongue-skinks"
    }, {
      "name": "EasternBlueTongueSkinks",
      "slug": "eastern-blue-tongue-skinks"
    }, {
      "name": "HalmaheraBlueTongueSkinks",
      "slug": "halmahera-blue-tongue-skinks"
    }, {
      "name": "IndonesianBlueTongueSkinks",
      "slug": "indonesian-blue-tongue-skinks"
    }, {
      "name": "NorthernBlueTongueSkinks",
      "slug": "northern-blue-tongue-skinks"
    }, {
      "name": "ShinglebackBlueTongueSkinks",
      "slug": "shingleback-blue-tongue-skinks"
    }, {
      "name": "WesternBlueTongueSkinks",
      "slug": "western-blue-tongue-skinks"
    }, {
      "name": "CommonSunSkinks",
      "slug": "common-sun-skinks"
    }, {
      "name": "EmeraldTreeSkink",
      "slug": "emerald-tree-skink"
    }, {
      "name": "FireSkinks",
      "slug": "fire-skinks"
    }, {
      "name": "FiveLinedSkinks",
      "slug": "five-lined-skinks"
    }, {
      "name": "GidgeeSkinks",
      "slug": "gidgee-skinks"
    }, {
      "name": "KenyanZebraSkinks",
      "slug": "kenyan-zebra-skinks"
    }, {
      "name": "OcellatedSkinks",
      "slug": "ocellated-skinks"
    }, {
      "name": "PetersBandedSkinks",
      "slug": "peters-banded-skinks"
    }, {
      "name": "PinkTonguedSkinks",
      "slug": "pink-tongued-skinks"
    }, {
      "name": "RainbowSkinks",
      "slug": "rainbow-skinks"
    }, {
      "name": "RedEyedCrocodileSkinks",
      "slug": "red-eyed-crocodile-skinks"
    }, {
      "name": "SandfishSkinks",
      "slug": "sandfish-skinks"
    }, {
      "name": "BerberSkinks",
      "slug": "berber-skinks"
    }, {
      "name": "SolomonIslandSkinks",
      "slug": "solomon-island-skinks"
    }, {
      "name": "WedgeSnoutedSkinks",
      "slug": "wedge-snouted-skinks"
    }, {
      "name": "Tegus",
      "slug": "tegus"
    }, {
      "name": "ArgentineTegus",
      "slug": "argentine-tegus"
    }, {
      "name": "ColombianTegus",
      "slug": "colombian-tegus"
    }, {
      "name": "Uromastyx",
      "slug": "uromastyx"
    }, {
      "name": "EgyptianUromastyx",
      "slug": "egyptian-uromastyx"
    }, {
      "name": "MacfadyensUromastyx",
      "slug": "macfadyens-uromastyx"
    }, {
      "name": "MoroccanUromastyx",
      "slug": "moroccan-uromastyx"
    }, {
      "name": "OcellatedUromastyx",
      "slug": "ocellated-uromastyx"
    }, {
      "name": "OrnateUromastyx",
      "slug": "ornate-uromastyx"
    }, {
      "name": "SudanUromastyx",
      "slug": "sudan-uromastyx"
    }, {
      "name": "OtherLizards",
      "slug": "other-lizards"
    }, {
      "name": "ArmadilloLizards",
      "slug": "armadillo-lizards"
    }, {
      "name": "AustralianWaterDragons",
      "slug": "australian-water-dragons"
    }, {
      "name": "BalkanGreenLizards",
      "slug": "balkan-green-lizards"
    }, {
      "name": "BoydsForestDragons",
      "slug": "boyds-forest-dragons"
    }, {
      "name": "BrazilianGalliwasps",
      "slug": "brazilian-galliwasps"
    }, {
      "name": "BrownBasilisks",
      "slug": "brown-basilisks"
    }, {
      "name": "ButterflyAgamas",
      "slug": "butterfly-agamas"
    }, {
      "name": "CaimanLizards",
      "slug": "caiman-lizards"
    }, {
      "name": "ChineseCrocodileLizards",
      "slug": "chinese-crocodile-lizards"
    }, {
      "name": "Chuckwallas",
      "slug": "chuckwallas"
    }, {
      "name": "ClownAgamas",
      "slug": "clown-agamas"
    }, {
      "name": "DesertHornedLizards",
      "slug": "desert-horned-lizards"
    }, {
      "name": "EasternCollaredLizards",
      "slug": "eastern-collared-lizards"
    }, {
      "name": "EasternGlassLizards",
      "slug": "eastern-glass-lizards"
    }, {
      "name": "EasternWaterDragons",
      "slug": "eastern-water-dragons"
    }, {
      "name": "ElegantEyedLizards",
      "slug": "elegant-eyed-lizards"
    }, {
      "name": "EmeraldSwifts",
      "slug": "emerald-swifts"
    }, {
      "name": "FrilledLizards",
      "slug": "frilled-lizards"
    }, {
      "name": "GiantPlatedLizards",
      "slug": "giant-plated-lizards"
    }, {
      "name": "GippslandWaterDragons",
      "slug": "gippsland-water-dragons"
    }, {
      "name": "GreenAmeiva",
      "slug": "green-ameiva"
    }, {
      "name": "PlumedBasilisks",
      "slug": "plumed-basilisks"
    }, {
      "name": "GreenKeelBelliedLizards",
      "slug": "green-keel-bellied-lizards"
    }, {
      "name": "HumpSnoutLizards",
      "slug": "hump-snout-lizards"
    }, {
      "name": "JeweledLacerta",
      "slug": "jeweled-lacerta"
    }, {
      "name": "LeopardLizards",
      "slug": "leopard-lizards"
    }, {
      "name": "LongTailedGrassLizards",
      "slug": "long-tailed-grass-lizards"
    }, {
      "name": "MagagascarPlatedLizards",
      "slug": "magagascar-plated-lizards"
    }, {
      "name": "MexicanAlligatorLizards",
      "slug": "mexican-alligator-lizards"
    }, {
      "name": "PygmyLizards",
      "slug": "pygmy-lizards"
    }, {
      "name": "RainbowWhiptails",
      "slug": "rainbow-whiptails"
    }, {
      "name": "PaintedAgamas",
      "slug": "painted-agamas"
    }, {
      "name": "PhilippineSailfinLizards",
      "slug": "philippine-sailfin-lizards"
    }, {
      "name": "ShieldTailedAgamas",
      "slug": "shield-tailed-agamas"
    }, {
      "name": "SpidermanAgamas",
      "slug": "spiderman-agamas"
    }, {
      "name": "SteppeRunners",
      "slug": "steppe-runners"
    }, {
      "name": "SudanPlatedLizards",
      "slug": "sudan-plated-lizards"
    }, {
      "name": "SungazerLizards",
      "slug": "sungazer-lizards"
    }, {
      "name": "TexasAlligatorLizards",
      "slug": "texas-alligator-lizards"
    }, {
      "name": "WebersSailfinLizards",
      "slug": "webers-sailfin-lizards"
    }, {
      "name": "YellowSpottedNightLizards",
      "slug": "yellow-spotted-night-lizards"
    }, {
      "name": "Turtles",
      "slug": "turtles"
    }, {
      "name": "AquaticTurtles",
      "slug": "aquatic-turtles"
    }, {
      "name": "AfricanSideneckTurtles",
      "slug": "african-sideneck-turtles"
    }, {
      "name": "MataMataTurtles",
      "slug": "mata-mata-turtles"
    }, {
      "name": "SnakeNeckTurtles",
      "slug": "snake-neck-turtles"
    }, {
      "name": "FloridaSoftshellTurtles",
      "slug": "florida-softshell-turtles"
    }, {
      "name": "SpinySoftshellTurtles",
      "slug": "spiny-softshell-turtles"
    }, {
      "name": "PigNosedTurtles",
      "slug": "pig-nosed-turtles"
    }, {
      "name": "AfricanHelmetedTurtles",
      "slug": "african-helmeted-turtles"
    }, {
      "name": "ArgentineSideneckTurtles",
      "slug": "argentine-sideneck-turtles"
    }, {
      "name": "BangladeshBlackTurtles",
      "slug": "bangladesh-black-turtles"
    }, {
      "name": "CommonMapTurtles",
      "slug": "common-map-turtles"
    }, {
      "name": "CommonSnappingTurtles",
      "slug": "common-snapping-turtles"
    }, {
      "name": "JapanesePondTurtles",
      "slug": "japanese-pond-turtles"
    }, {
      "name": "MississippiMapTurtles",
      "slug": "mississippi-map-turtles"
    }, {
      "name": "MudTurtles",
      "slug": "mud-turtles"
    }, {
      "name": "MuskTurtles",
      "slug": "musk-turtles"
    }, {
      "name": "PaintedTurtles",
      "slug": "painted-turtles"
    }, {
      "name": "PeninsulaCooters",
      "slug": "peninsula-cooters"
    }, {
      "name": "PinkBellySideneckTurtles",
      "slug": "pink-belly-sideneck-turtles"
    }, {
      "name": "RedEaredSliders",
      "slug": "red-eared-sliders"
    }, {
      "name": "ReevesTurtles",
      "slug": "reeves-turtles"
    }, {
      "name": "RiverCooters",
      "slug": "river-cooters"
    }, {
      "name": "SpottedTurtles",
      "slug": "spotted-turtles"
    }, {
      "name": "ToadHeadedTurtles",
      "slug": "toad-headed-turtles"
    }, {
      "name": "VietnamesePondTurtles",
      "slug": "vietnamese-pond-turtles"
    }, {
      "name": "WoodTurtles",
      "slug": "wood-turtles"
    }, {
      "name": "YellowBelliedSliders",
      "slug": "yellow-bellied-sliders"
    }, {
      "name": "BoxTurtles",
      "slug": "box-turtles"
    }, {
      "name": "AsianBoxTurtles",
      "slug": "asian-box-turtles"
    }, {
      "name": "EasternBoxTurtles",
      "slug": "eastern-box-turtles"
    }, {
      "name": "OrnateBoxTurtles",
      "slug": "ornate-box-turtles"
    }, {
      "name": "ThreeToedBoxTurtles",
      "slug": "three-toed-box-turtles"
    }, {
      "name": "Tortoises",
      "slug": "tortoises"
    }, {
      "name": "AldabraTortoises",
      "slug": "aldabra-tortoises"
    }, {
      "name": "EgyptianTortoises",
      "slug": "egyptian-tortoises"
    }, {
      "name": "GreekTortoises",
      "slug": "greek-tortoises"
    }, {
      "name": "HermannsTortoises",
      "slug": "hermanns-tortoises"
    }, {
      "name": "IndianStarTortoises",
      "slug": "indian-star-tortoises"
    }, {
      "name": "LeopardTortoises",
      "slug": "leopard-tortoises"
    }, {
      "name": "MarginatedTortoises",
      "slug": "marginated-tortoises"
    }, {
      "name": "PancakeTortoises",
      "slug": "pancake-tortoises"
    }, {
      "name": "RadiatedTortoises",
      "slug": "radiated-tortoises"
    }, {
      "name": "RedFootedTortoises",
      "slug": "red-footed-tortoises"
    }, {
      "name": "RussianTortoises",
      "slug": "russian-tortoises"
    }, {
      "name": "SulcataTortoises",
      "slug": "sulcata-tortoises"
    }, {
      "name": "YellowFootedTortoises",
      "slug": "yellow-footed-tortoises"
    }, {
      "name": "OtherReptiles",
      "slug": "other-reptiles"
    }, {
      "name": "Amphibians",
      "slug": "amphibians"
    }, {
      "name": "Frogs",
      "slug": "frogs"
    }, {
      "name": "AfricanClawedFrogs",
      "slug": "african-clawed-frogs"
    }, {
      "name": "AfricanDwarfFrogs",
      "slug": "african-dwarf-frogs"
    }, {
      "name": "AmazonMilkFrogs",
      "slug": "amazon-milk-frogs"
    }, {
      "name": "AmericanBullfrogs",
      "slug": "american-bullfrogs"
    }, {
      "name": "AsianPaintedFrogs",
      "slug": "asian-painted-frogs"
    }, {
      "name": "BorneoLongEarFrog",
      "slug": "borneo-long-ear-frog"
    }, {
      "name": "BudgettsFrogs",
      "slug": "budgetts-frogs"
    }, {
      "name": "DartFrogs",
      "slug": "dart-frogs"
    }, {
      "name": "GoldenPoisonFrogs",
      "slug": "golden-poison-frogs"
    }, {
      "name": "LeopardFrogs",
      "slug": "leopard-frogs"
    }, {
      "name": "MalaysianHornedFrogs",
      "slug": "malaysian-horned-frogs"
    }, {
      "name": "PacmanFrogs",
      "slug": "pacman-frogs"
    }, {
      "name": "PixieFrogs",
      "slug": "pixie-frogs"
    }, {
      "name": "ReedFrogs",
      "slug": "reed-frogs"
    }, {
      "name": "SolomonIslandLeafFrogs",
      "slug": "solomon-island-leaf-frogs"
    }, {
      "name": "TomatoFrogs",
      "slug": "tomato-frogs"
    }, {
      "name": "TreeFrogs",
      "slug": "tree-frogs"
    }, {
      "name": "ClownTreeFrogs",
      "slug": "clown-tree-frogs"
    }, {
      "name": "GlassFrogs",
      "slug": "glass-frogs"
    }, {
      "name": "GrayTreeFrogs",
      "slug": "gray-tree-frogs"
    }, {
      "name": "GreenTreeFrogs",
      "slug": "green-tree-frogs"
    }, {
      "name": "RedEyedGreenTreeFrogs",
      "slug": "red-eyed-green-tree-frogs"
    }, {
      "name": "VietnameseMossyFrogs",
      "slug": "vietnamese-mossy-frogs"
    }, {
      "name": "WaxyMonkeyTreeFrogs",
      "slug": "waxy-monkey-tree-frogs"
    }, {
      "name": "WhiteLippedTreeFrogs",
      "slug": "white-lipped-tree-frogs"
    }, {
      "name": "WhitesTreeFrogs",
      "slug": "whites-tree-frogs"
    }, {
      "name": "Toads",
      "slug": "toads"
    }, {
      "name": "AmericanToads",
      "slug": "american-toads"
    }, {
      "name": "CaneToads",
      "slug": "cane-toads"
    }, {
      "name": "ColoradoRiverToads",
      "slug": "colorado-river-toads"
    }, {
      "name": "EuropeanGreenToads",
      "slug": "european-green-toads"
    }, {
      "name": "FireBelliedToads",
      "slug": "fire-bellied-toads"
    }, {
      "name": "SurinamToads",
      "slug": "surinam-toads"
    }, {
      "name": "YellowSpottedClimbingToads",
      "slug": "yellow-spotted-climbing-toads"
    }, {
      "name": "Salamanders",
      "slug": "salamanders"
    }, {
      "name": "FireSalamanders",
      "slug": "fire-salamanders"
    }, {
      "name": "IdahoGiantSalamanders",
      "slug": "idaho-giant-salamanders"
    }, {
      "name": "Newts",
      "slug": "newts"
    }, {
      "name": "AlpineNewts",
      "slug": "alpine-newts"
    }, {
      "name": "CaliforniaNewts",
      "slug": "california-newts"
    }, {
      "name": "CrocodileNewts",
      "slug": "crocodile-newts"
    }, {
      "name": "KaisersSpottedNewts",
      "slug": "kaisers-spotted-newts"
    }, {
      "name": "LaosWartyNewts",
      "slug": "laos-warty-newts"
    }, {
      "name": "MandarinNewts",
      "slug": "mandarin-newts"
    }, {
      "name": "RedTailedKnobbyNewts",
      "slug": "red-tailed-knobby-newts"
    }, {
      "name": "SpanishRibbedNewts",
      "slug": "spanish-ribbed-newts"
    }, {
      "name": "OtherAmphibians",
      "slug": "other-amphibians"
    }, {
      "name": "Invertebrates",
      "slug": "invertebrates"
    }, {
      "name": "Beetles",
      "slug": "beetles"
    }, {
      "name": "BlueDeathFeigningBeetles",
      "slug": "blue-death-feigning-beetles"
    }, {
      "name": "Centipedes",
      "slug": "centipedes"
    }, {
      "name": "AfricanLongtailCentipedes",
      "slug": "african-longtail-centipedes"
    }, {
      "name": "SolomonIslandGiantCentipedes",
      "slug": "solomon-island-giant-centipedes"
    }, {
      "name": "Cockroaches",
      "slug": "cockroaches"
    }, {
      "name": "DiscoidRoaches",
      "slug": "discoid-roaches"
    }, {
      "name": "DubiaRoaches",
      "slug": "dubia-roaches"
    }, {
      "name": "GiantCaveRoaches",
      "slug": "giant-cave-roaches"
    }, {
      "name": "HissingRoaches",
      "slug": "hissing-roaches"
    }, {
      "name": "TurkestanRoaches",
      "slug": "turkestan-roaches"
    }, {
      "name": "Isopods",
      "slug": "isopods"
    }, {
      "name": "Mantises",
      "slug": "mantises"
    }, {
      "name": "ChineseMantises",
      "slug": "chinese-mantises"
    }, {
      "name": "DeadLeafMantises",
      "slug": "dead-leaf-mantises"
    }, {
      "name": "GhostMantises",
      "slug": "ghost-mantises"
    }, {
      "name": "GiantAfricanMantises",
      "slug": "giant-african-mantises"
    }, {
      "name": "GiantAsianMantises",
      "slug": "giant-asian-mantises"
    }, {
      "name": "IndianFlowerMantises",
      "slug": "indian-flower-mantises"
    }, {
      "name": "OrchidMantises",
      "slug": "orchid-mantises"
    }, {
      "name": "Millipedes",
      "slug": "millipedes"
    }, {
      "name": "GiantAfricanMillipedes",
      "slug": "giant-african-millipedes"
    }, {
      "name": "Scorpions",
      "slug": "scorpions"
    }, {
      "name": "AsianForestScorpion",
      "slug": "asian-forest-scorpion"
    }, {
      "name": "EmperorScorpion",
      "slug": "emperor-scorpion"
    }, {
      "name": "StickInsects",
      "slug": "stick-insects"
    }, {
      "name": "AnnamWalkingSticks",
      "slug": "annam-walking-sticks"
    }, {
      "name": "GiantPricklyStickInsects",
      "slug": "giant-prickly-stick-insects"
    }, {
      "name": "IndianStickInsects",
      "slug": "indian-stick-insects"
    }, {
      "name": "JungleNymphs",
      "slug": "jungle-nymphs"
    }, {
      "name": "PinkWingStickInsects",
      "slug": "pink-wing-stick-insects"
    }, {
      "name": "Tarantulas",
      "slug": "tarantulas"
    }, {
      "name": "AntillesPinktoeTarantulas",
      "slug": "antilles-pinktoe-tarantulas"
    }, {
      "name": "BrazilianBlueTarantulas",
      "slug": "brazilian-blue-tarantulas"
    }, {
      "name": "ChacoGoldenKneeTarantulas",
      "slug": "chaco-golden-knee-tarantulas"
    }, {
      "name": "ChileanRoseTarantulas",
      "slug": "chilean-rose-tarantulas"
    }, {
      "name": "ColumbiaRedlegTarantulas",
      "slug": "columbia-redleg-tarantulas"
    }, {
      "name": "CommonBluebloomTarantulas",
      "slug": "common-bluebloom-tarantulas"
    }, {
      "name": "CostaRicanZebraTarantulas",
      "slug": "costa-rican-zebra-tarantulas"
    }, {
      "name": "CurlyHairTarantulas",
      "slug": "curly-hair-tarantulas"
    }, {
      "name": "ElectricBlueTarantula",
      "slug": "electric-blue-tarantula"
    }, {
      "name": "GoldBandedSunburstDwarfTarantulas",
      "slug": "gold-banded-sunburst-dwarf-tarantulas"
    }, {
      "name": "GoldenBlueLeggedBaboonTarantulas",
      "slug": "golden-blue-legged-baboon-tarantulas"
    }, {
      "name": "GoliathBirdeaters",
      "slug": "goliath-birdeaters"
    }, {
      "name": "HaitianBrownTarantulas",
      "slug": "haitian-brown-tarantulas"
    }, {
      "name": "IndianBlueDwarfTarantulas",
      "slug": "indian-blue-dwarf-tarantulas"
    }, {
      "name": "MexicanRedKneeTarantulas",
      "slug": "mexican-red-knee-tarantulas"
    }, {
      "name": "NeonBlueLegTarantulas",
      "slug": "neon-blue-leg-tarantulas"
    }, {
      "name": "PinkZebraBeautyTarantulas",
      "slug": "pink-zebra-beauty-tarantulas"
    }, {
      "name": "PinktoeTarantulas",
      "slug": "pinktoe-tarantulas"
    }, {
      "name": "PumpkinPatchTarantulas",
      "slug": "pumpkin-patch-tarantulas"
    }, {
      "name": "SocotraIslandBlueBaboonTarantulas",
      "slug": "socotra-island-blue-baboon-tarantulas"
    }, {
      "name": "TigerRumpTarantulas",
      "slug": "tiger-rump-tarantulas"
    }, {
      "name": "TrapDoorTarantulas",
      "slug": "trap-door-tarantulas"
    }, {
      "name": "TrinidadChevronTarantulas",
      "slug": "trinidad-chevron-tarantulas"
    }, {
      "name": "TrinidadOliveTarantulas",
      "slug": "trinidad-olive-tarantulas"
    }, {
      "name": "TrueSpiders",
      "slug": "true-spiders"
    }, {
      "name": "AustralianBarkSpiders",
      "slug": "australian-bark-spiders"
    }, {
      "name": "HuntsmanSpiders",
      "slug": "huntsman-spiders"
    }, {
      "name": "JumpingSpiders",
      "slug": "jumping-spiders"
    }, {
      "name": "WolfSpiders",
      "slug": "wolf-spiders"
    }, {
      "name": "OtherInvertebrates",
      "slug": "other-invertebrates"
    }, {
      "name": "GiantVinegaroons",
      "slug": "giant-vinegaroons"
    }, {
      "name": "TaillessWhipScorpions",
      "slug": "tailless-whip-scorpions"
    }, {
      "name": "VelvetAnts",
      "slug": "velvet-ants"
    }
  ]